# No automatic build triggering.
trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python36:
      python.version: '3.6'

variables: 
  artifact_dir: $(Build.ArtifactStagingDirectory)\build

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    echo $(Build.ArtifactStagingDirectory)
    dir /s
  displayName: 'debug'

- script: |
    python -m pip install --upgrade pip
    pip install conan
  displayName: 'Install build dependencies'


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '*.xml'
    searchFolder: $(Build.SourcesDirectory)/build/bin

- script: |
    test_exe.exe -r junit -o test_exe.xml
  workingDirectory: build/bin
  displayName: 'run test exe'



- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(artifact_dir)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'Test_feed'
    vstsFeedPackagePublish: 'test_package'
    versionOption: 'patch'
